name: Build
on: [push]

jobs:
  Qemu_on_ubuntu_20_04:
    name: Building qemu for Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y git libglib2.0-dev libfdt-dev \
            libpixman-1-dev zlib1g-dev ninja-build python3-pip
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Configure and build
        run: |
          mkdir build
          cd build
          ../configure --target-list=ppc-softmmu \
            --disable-vnc --disable-sdl --disable-gnutls --disable-nettle --disable-gtk
          make -j2
          cd ..
      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp build/qemu-system-ppc artifacts
          cp pc-bios/module_* artifacts
          cp scripts/qemu-ifup artifacts
      - name: Uploade artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qemu-ppc476-ubuntu-20.04
          path: artifacts/*
